<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.7.26381.103" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="Microsoft.Testing.Platform.MSBuild" Version="2.3.3" />
  </ItemGroup>
</Project>
